In [1]:
# Importing the libraries
import pandas as pd
import numpy as np

In [3]:
# Changing the working directory
cd C:\Users\admin\Downloads

C:\Users\admin\Downloads

In [4]:
# Loading the dataset
df = pd.read_csv('Nashville Housing Data.csv')

In [5]:
# Shows the top 5 rows of the DataFrame
df.head()

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE","April 9, 2013",240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE","June 10, 2014",366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE","September 26, 2016",435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE","January 29, 2016",255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE","October 10, 2014",278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0

In [6]:
# Checking the column data types
df.dtypes

UniqueID             int64
ParcelID            object
LandUse             object
PropertyAddress     object
SaleDate            object
SalePrice           object
LegalReference      object
SoldAsVacant        object
OwnerName           object
OwnerAddress        object
Acreage            float64
TaxDistrict         object
LandValue          float64
BuildingValue      float64
TotalValue         float64
YearBuilt          float64
Bedrooms           float64
FullBath           float64
HalfBath           float64
dtype: object

In [7]:
# Coverting SaleDate column to datetime format
df['SaleDate'] = pd.to_datetime(df['SaleDate'])

In [8]:
# Changing the datatype in  YearBuilt column 
df['YearBuilt'] = df['YearBuilt'].astype(object)

In [9]:
# Checking for null values
df.isnull().sum()

UniqueID               0
ParcelID               0
LandUse                0
PropertyAddress       29
SaleDate               0
SalePrice              0
LegalReference         0
SoldAsVacant           0
OwnerName          31216
OwnerAddress       30462
Acreage            30462
TaxDistrict        30462
LandValue          30462
BuildingValue      30462
TotalValue         30462
YearBuilt          32314
Bedrooms           32320
FullBath           32202
HalfBath           32333
dtype: int64

In [10]:
# Sorting the DataFrame by the ParcelID column
df = df.sort_values(by = ['ParcelID'])

In [11]:
# groupby() method groups the DataFrame by the ParcelID  
# 'ffill' & 'bfill' methods forward fills and backward fills null values in PropertyAddress column for each ParcelID

df['PropertyAddress'] = df.groupby('ParcelID')['PropertyAddress'].fillna(method = 'ffill').fillna(method = 'bfill')

In [12]:
# Checking for any other null values in PropertyAddress column
df['PropertyAddress'].isnull().sum()

0

In [15]:
# fillna method fills the null values in all the other columns with 'Not Applicable'
# inplace = True makes changes to our underlying Data
df.fillna('Not Applicable', inplace = True)

In [17]:
# Checking for the unique entries in SoldAsVacant column
df['SoldAsVacant'].unique()

array(['No', 'N', 'Yes', 'Y'], dtype=object)

In [18]:
# Replace method replaces the 'N' and 'Y' with 'No' and 'Yes' respectively
df['SoldAsVacant'] = df['SoldAsVacant'].replace({'N':'No', 'Y':'Yes'})

In [19]:
# str.split method splits PropertyAddress column into PropertyPostalAddress & PropertyCityAddress
# We use expand = True argument so that the split elements expand out into separate columns
# In this case our separator is a comma ','
df[['PropertyPostalAddress', 'PropertyCityAddress']] = df['PropertyAddress'].str.split(',', expand = True)

In [20]:
# Splitting OwnerAddress column into 3 columns i.e OwnerPostalAddress, OwnerCity & OwnerState
# Our separator is a comma ','
df[['OwnerPostalAddress', 'OwnerCity', 'OwnerState']] = df['OwnerAddress'].str.split(',', expand = True)

In [21]:
#  Using df.drop() method to remove the unsplit PropertyAddress & OwnerAddress columns
# inplace = True modifies the underlying Data
df.drop(columns = ['PropertyAddress','OwnerAddress'], axis = 1, inplace = True)

In [22]:
# Returns all the column headers as a list
list(df.columns)

['UniqueID ',
 'ParcelID',
 'LandUse',
 'SaleDate',
 'SalePrice',
 'LegalReference',
 'SoldAsVacant',
 'OwnerName',
 'Acreage',
 'TaxDistrict',
 'LandValue',
 'BuildingValue',
 'TotalValue',
 'YearBuilt',
 'Bedrooms',
 'FullBath',
 'HalfBath',
 'PropertyPostalAddress',
 'PropertyCityAddress',
 'OwnerPostalAddress',
 'OwnerCity',
 'OwnerState']

In [23]:
# Reorder the columns of the DataFrame using df.insert() & df.pop() method
# PropertyPostalAddress column to index 3
df.insert(3, 'PropertyPostalAddress', df.pop('PropertyPostalAddress'))

In [24]:
# PropertyCityAddress column to index 4
df.insert(4, 'PropertyCityAddress', df.pop('PropertyCityAddress'))

In [25]:
# OwnerPostalAddress column to index 10
df.insert(10, 'OwnerPostalAddress', df.pop('OwnerPostalAddress'))

In [26]:
# OwnerCity column to index 11
df.insert(11, 'OwnerCity', df.pop('OwnerCity'))

In [27]:
# OwnerState column to index 12
df.insert(12, 'OwnerState', df.pop('OwnerState'))

In [28]:
# Returns our DataFrame with the new column indexes
df

,UniqueID,ParcelID,LandUse,PropertyPostalAddress,PropertyCityAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,...,OwnerState,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,1808 FOX CHASE DR,GOODLETTSVILLE,2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE",...,TN,2.3,GENERAL SERVICES DISTRICT,50000,168200,235700,1986,3,3,0
1,16918,007 00 0 130.00,SINGLE FAMILY,1832 FOX CHASE DR,GOODLETTSVILLE,2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE",...,TN,3.5,GENERAL SERVICES DISTRICT,50000,264100,319000,1998,3,3,2
2,54582,007 00 0 138.00,SINGLE FAMILY,1864 FOX CHASE DR,GOODLETTSVILLE,2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE",...,TN,2.9,GENERAL SERVICES DISTRICT,50000,216200,298000,1987,4,3,0
3,43070,007 00 0 143.00,SINGLE FAMILY,1853 FOX CHASE DR,GOODLETTSVILLE,2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.",...,TN,2.6,GENERAL SERVICES DISTRICT,50000,147300,197300,1985,3,3,0
4,22714,007 00 0 149.00,SINGLE FAMILY,1829 FOX CHASE DR,GOODLETTSVILLE,2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.",...,TN,2,GENERAL SERVICES DISTRICT,50000,152300,202300,1984,4,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,30469,188 10 0A 101.00,SINGLE FAMILY,1435 WINDING CREEK DR,NOLENSVILLE,2015-05-27,157500,20150608-0053286,No,Not Applicable,...,None,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable
56473,27707,188 10 0A 107.00,SINGLE FAMILY,1423 WINDING CREEK DR,NOLENSVILLE,2015-03-02,145000,20150304-0019013,No,Not Applicable,...,None,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable
56474,52709,188 10 0A 118.00,VACANT RESIDENTIAL LAND,1804 GRACE POINT LN,NOLENSVILLE,2016-08-16,234611,20160819-0087214,Yes,Not Applicable,...,None,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable
56475,54042,188 10 0A 121.00,VACANT RESIDENTIAL LAND,1709 PARK TERRACE LN,NOLENSVILLE,2016-09-07,93844,20160919-0098411,Yes,Not Applicable,...,None,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable
56476,54043,188 10 0A 122.00,VACANT RESIDENTIAL LAND,1713 PARK TERRACE LN,NOLENSVILLE,2016-09-07,93844,20160919-0098411,Yes,Not Applicable,...,None,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable